api=../api
tags=../ref/Tags
github=https://github.com/grace-profiles/base
sourcedir=.
sourceRepo=https://github.com/grace-profiles/base/edit/2024.2.x/docs
safe=UNSAFE
title=Grace Profile : Base
subtitle=A Grace profile for other profiles to extend from
authors=Michael Yan
copyright=Copyright &copy; 2022-2026 Michael Yan and the original authors. The content is licensed under a Creative Commons Attribution 4.0 International (CC BY SA 4.0) license.
